version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: perfume_mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: perfume_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: perfume_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db

  api:
    build: .
    container_name: perfume_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=perfume_db
    depends_on:
      - db

volumes:
  db_data:
